apiVersion: security.btp.sap.crossplane.io/v1alpha1
kind: SubaccountApiCredential
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/subaccountapicredential
  labels:
    testing.upbound.io/example-name: with-secret
  name: with-secret
spec:
  forProvider:
    name: subaccount-api-credential-with-secret
    readOnly: false
    subaccountSelector:
      matchLabels:
        testing.upbound.io/example-name: example
