/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this CloudManagement.
func (mg *CloudManagement) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.SubaccountGuid,
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.ForProvider.SubaccountRef,
		Selector:     mg.Spec.ForProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubaccountGuid")
	}
	mg.Spec.ForProvider.SubaccountGuid = rsp.ResolvedValue
	mg.Spec.ForProvider.SubaccountRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ServiceManagerSecret,
		Extract:      ServiceManagerSecret(),
		Reference:    mg.Spec.ForProvider.ServiceManagerRef,
		Selector:     mg.Spec.ForProvider.ServiceManagerSelector,
		To: reference.To{
			List:    &ServiceManagerList{},
			Managed: &ServiceManager{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceManagerSecret")
	}
	mg.Spec.ForProvider.ServiceManagerSecret = rsp.ResolvedValue
	mg.Spec.ForProvider.ServiceManagerRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ServiceManagerSecretNamespace,
		Extract:      ServiceManagerSecretNamespace(),
		Reference:    mg.Spec.ForProvider.ServiceManagerRef,
		Selector:     mg.Spec.ForProvider.ServiceManagerSelector,
		To: reference.To{
			List:    &ServiceManagerList{},
			Managed: &ServiceManager{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceManagerSecretNamespace")
	}
	mg.Spec.ForProvider.ServiceManagerSecretNamespace = rsp.ResolvedValue
	mg.Spec.ForProvider.ServiceManagerRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Directory.
func (mg *Directory) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.DirectoryGuid,
		Extract:      DirectoryUuid(),
		Reference:    mg.Spec.ForProvider.DirectoryRef,
		Selector:     mg.Spec.ForProvider.DirectorySelector,
		To: reference.To{
			List:    &DirectoryList{},
			Managed: &Directory{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DirectoryGuid")
	}
	mg.Spec.ForProvider.DirectoryGuid = rsp.ResolvedValue
	mg.Spec.ForProvider.DirectoryRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DirectoryID),
		Extract:      DirectoryUuid(),
		Reference:    mg.Spec.ForProvider.DirectoryRef,
		Selector:     mg.Spec.ForProvider.DirectorySelector,
		To: reference.To{
			List:    &DirectoryList{},
			Managed: &Directory{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DirectoryID")
	}
	mg.Spec.ForProvider.DirectoryID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DirectoryRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DirectoryID),
		Extract:      DirectoryUuid(),
		Reference:    mg.Spec.InitProvider.DirectoryRef,
		Selector:     mg.Spec.InitProvider.DirectorySelector,
		To: reference.To{
			List:    &DirectoryList{},
			Managed: &Directory{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DirectoryID")
	}
	mg.Spec.InitProvider.DirectoryID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DirectoryRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Entitlement.
func (mg *Entitlement) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.SubaccountGuid,
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.ForProvider.SubaccountRef,
		Selector:     mg.Spec.ForProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubaccountGuid")
	}
	mg.Spec.ForProvider.SubaccountGuid = rsp.ResolvedValue
	mg.Spec.ForProvider.SubaccountRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ServiceManager.
func (mg *ServiceManager) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.SubaccountGuid,
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.ForProvider.SubaccountRef,
		Selector:     mg.Spec.ForProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubaccountGuid")
	}
	mg.Spec.ForProvider.SubaccountGuid = rsp.ResolvedValue
	mg.Spec.ForProvider.SubaccountRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ServicePlan.
func (mg *ServicePlan) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ServiceManagerSecret,
		Extract:      ServiceManagerSecret(),
		Reference:    mg.Spec.ForProvider.ServiceManagerRef,
		Selector:     mg.Spec.ForProvider.ServiceManagerSelector,
		To: reference.To{
			List:    &ServiceManagerList{},
			Managed: &ServiceManager{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceManagerSecret")
	}
	mg.Spec.ForProvider.ServiceManagerSecret = rsp.ResolvedValue
	mg.Spec.ForProvider.ServiceManagerRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ServiceManagerSecretNamespace,
		Extract:      ServiceManagerSecretNamespace(),
		Reference:    mg.Spec.ForProvider.ServiceManagerRef,
		Selector:     mg.Spec.ForProvider.ServiceManagerSelector,
		To: reference.To{
			List:    &ServiceManagerList{},
			Managed: &ServiceManager{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceManagerSecretNamespace")
	}
	mg.Spec.ForProvider.ServiceManagerSecretNamespace = rsp.ResolvedValue
	mg.Spec.ForProvider.ServiceManagerRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Subaccount.
func (mg *Subaccount) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.GlobalAccountGuid,
		Extract:      GlobalAccountUuid(),
		Reference:    mg.Spec.ForProvider.GlobalAccountRef,
		Selector:     mg.Spec.ForProvider.GlobalAccountSelector,
		To: reference.To{
			List:    &GlobalAccountList{},
			Managed: &GlobalAccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GlobalAccountGuid")
	}
	mg.Spec.ForProvider.GlobalAccountGuid = rsp.ResolvedValue
	mg.Spec.ForProvider.GlobalAccountRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.DirectoryGuid,
		Extract:      DirectoryUuid(),
		Reference:    mg.Spec.ForProvider.DirectoryRef,
		Selector:     mg.Spec.ForProvider.DirectorySelector,
		To: reference.To{
			List:    &DirectoryList{},
			Managed: &Directory{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DirectoryGuid")
	}
	mg.Spec.ForProvider.DirectoryGuid = rsp.ResolvedValue
	mg.Spec.ForProvider.DirectoryRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceInstanceID),
		Extract:      SubaccountServiceInstanceId(),
		Reference:    mg.Spec.ForProvider.SubaccountServiceInstanceRef,
		Selector:     mg.Spec.ForProvider.SubaccountServiceInstanceSelector,
		To: reference.To{
			List:    &SubaccountServiceInstanceList{},
			Managed: &SubaccountServiceInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceInstanceID")
	}
	mg.Spec.ForProvider.ServiceInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubaccountServiceInstanceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubaccountID),
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.ForProvider.SubaccountRef,
		Selector:     mg.Spec.ForProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubaccountID")
	}
	mg.Spec.ForProvider.SubaccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubaccountRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServiceInstanceID),
		Extract:      SubaccountServiceInstanceId(),
		Reference:    mg.Spec.InitProvider.SubaccountServiceInstanceRef,
		Selector:     mg.Spec.InitProvider.SubaccountServiceInstanceSelector,
		To: reference.To{
			List:    &SubaccountServiceInstanceList{},
			Managed: &SubaccountServiceInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServiceInstanceID")
	}
	mg.Spec.InitProvider.ServiceInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubaccountServiceInstanceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubaccountID),
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.InitProvider.SubaccountRef,
		Selector:     mg.Spec.InitProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubaccountID")
	}
	mg.Spec.InitProvider.SubaccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubaccountRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubaccountID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SubaccountRef,
		Selector:     mg.Spec.ForProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubaccountID")
	}
	mg.Spec.ForProvider.SubaccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubaccountRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubaccountID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.SubaccountRef,
		Selector:     mg.Spec.InitProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubaccountID")
	}
	mg.Spec.InitProvider.SubaccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubaccountRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceplanID),
		Extract:      ServicePlanId(),
		Reference:    mg.Spec.ForProvider.ServicePlanRef,
		Selector:     mg.Spec.ForProvider.ServicePlanSelector,
		To: reference.To{
			List:    &ServicePlanList{},
			Managed: &ServicePlan{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceplanID")
	}
	mg.Spec.ForProvider.ServiceplanID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServicePlanRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubaccountID),
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.ForProvider.SubaccountRef,
		Selector:     mg.Spec.ForProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubaccountID")
	}
	mg.Spec.ForProvider.SubaccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubaccountRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServiceplanID),
		Extract:      ServicePlanId(),
		Reference:    mg.Spec.InitProvider.ServicePlanRef,
		Selector:     mg.Spec.InitProvider.ServicePlanSelector,
		To: reference.To{
			List:    &ServicePlanList{},
			Managed: &ServicePlan{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServiceplanID")
	}
	mg.Spec.InitProvider.ServiceplanID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServicePlanRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubaccountID),
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.InitProvider.SubaccountRef,
		Selector:     mg.Spec.InitProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubaccountID")
	}
	mg.Spec.InitProvider.SubaccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubaccountRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Subscription.
func (mg *Subscription) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.CloudManagementSecret,
		Extract:      CloudManagementSecret(),
		Reference:    mg.Spec.CloudManagementRef,
		Selector:     mg.Spec.CloudManagementSelector,
		To: reference.To{
			List:    &CloudManagementList{},
			Managed: &CloudManagement{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.CloudManagementSecret")
	}
	mg.Spec.CloudManagementSecret = rsp.ResolvedValue
	mg.Spec.CloudManagementRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.CloudManagementSecretNamespace,
		Extract:      CloudManagementSecretSecretNamespace(),
		Reference:    mg.Spec.CloudManagementRef,
		Selector:     mg.Spec.CloudManagementSelector,
		To: reference.To{
			List:    &CloudManagementList{},
			Managed: &CloudManagement{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.CloudManagementSecretNamespace")
	}
	mg.Spec.CloudManagementSecretNamespace = rsp.ResolvedValue
	mg.Spec.CloudManagementRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this WrappedServiceInstance.
func (mg *WrappedServiceInstance) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceplanID),
		Extract:      ServicePlanId(),
		Reference:    mg.Spec.ForProvider.ServicePlanRef,
		Selector:     mg.Spec.ForProvider.ServicePlanSelector,
		To: reference.To{
			List:    &ServicePlanList{},
			Managed: &ServicePlan{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceplanID")
	}
	mg.Spec.ForProvider.ServiceplanID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServicePlanRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubaccountID),
		Extract:      SubaccountUuid(),
		Reference:    mg.Spec.ForProvider.SubaccountRef,
		Selector:     mg.Spec.ForProvider.SubaccountSelector,
		To: reference.To{
			List:    &SubaccountList{},
			Managed: &Subaccount{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubaccountID")
	}
	mg.Spec.ForProvider.SubaccountID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubaccountRef = rsp.ResolvedReference

	return nil
}
