/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TfSubaccountInitParameters struct {

	// (Boolean) Shows whether the subaccount can use beta services and applications.
	// Shows whether the subaccount can use beta services and applications.
	BetaEnabled *bool `json:"betaEnabled,omitempty" tf:"beta_enabled,omitempty"`

	// facing UIs.
	// A description of the subaccount for customer-facing UIs.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Map of Set of String) The set of words or phrases assigned to the subaccount.
	// The set of words or phrases assigned to the subaccount.
	Labels map[string][]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The ID of the subaccount’s parent entity. If the subaccount is located directly in the global account (not in a directory), then this is the ID of the global account.
	// The ID of the subaccount’s parent entity. If the subaccount is located directly in the global account (not in a directory), then this is the ID of the global account.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) The region in which the subaccount was created.
	// The region in which the subaccount was created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The subdomain that becomes part of the path used to access the authorization tenant of the subaccount. Must be unique within the defined region and cannot be changed after the subaccount has been created.
	// The subdomain that becomes part of the path used to access the authorization tenant of the subaccount. Must be unique within the defined region and cannot be changed after the subaccount has been created.
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`

	// critical accounts in production systems. Do not apply for subaccounts that are used for nonproduction purposes, such as development, testing, and demos. Applying this setting this does not modify the subaccount. Possible values are:
	// Shows whether the subaccount is used for production purposes. This flag can help your cloud operator to take appropriate action when handling incidents that are related to mission-critical accounts in production systems. Do not apply for subaccounts that are used for nonproduction purposes, such as development, testing, and demos. Applying this setting this does not modify the subaccount. Possible values are:
	//
	// | value | description |
	// | --- | --- |
	// | `UNSET` | Global account or subaccount admin has not set the production-relevancy flag (default value). |
	// | `NOT_USED_FOR_PRODUCTION` | The subaccount is not used for production purposes. |
	// | `USED_FOR_PRODUCTION` | The subaccount is used for production purposes. |
	Usage *string `json:"usage,omitempty" tf:"usage,omitempty"`
}

type TfSubaccountObservation struct {

	// (Boolean) Shows whether the subaccount can use beta services and applications.
	// Shows whether the subaccount can use beta services and applications.
	BetaEnabled *bool `json:"betaEnabled,omitempty" tf:"beta_enabled,omitempty"`

	// (String) The details of the user that created the subaccount.
	// The details of the user that created the subaccount.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// (String) The date and time when the resource was created in RFC3339 format.
	// The date and time when the resource was created in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
	CreatedDate *string `json:"createdDate,omitempty" tf:"created_date,omitempty"`

	// facing UIs.
	// A description of the subaccount for customer-facing UIs.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of the subaccount.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of Set of String) The set of words or phrases assigned to the subaccount.
	// The set of words or phrases assigned to the subaccount.
	Labels map[string][]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The date and time when the resource was last modified in RFC3339 format.
	// The date and time when the resource was last modified in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
	LastModified *string `json:"lastModified,omitempty" tf:"last_modified,omitempty"`

	// (Set of String) The features of parent entity of the subaccount.
	// The features of parent entity of the subaccount.
	// +listType=set
	ParentFeatures []*string `json:"parentFeatures,omitempty" tf:"parent_features,omitempty"`

	// (String) The ID of the subaccount’s parent entity. If the subaccount is located directly in the global account (not in a directory), then this is the ID of the global account.
	// The ID of the subaccount’s parent entity. If the subaccount is located directly in the global account (not in a directory), then this is the ID of the global account.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) The region in which the subaccount was created.
	// The region in which the subaccount was created.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The current state of the subaccount. Possible values are:
	// The current state of the subaccount. Possible values are:
	//
	// | state | description |
	// | --- | --- |
	// | `OK` | The CRUD operation or series of operations completed successfully. |
	// | `STARTED` | CRUD operation on the subaccount has started. |
	// | `CANCELED` | The operation or processing was canceled by the operator. |
	// | `PROCESSING` | A series of operations related to the subaccount are in progress. |
	// | `PROCESSING_FAILED` | The processing operations failed. |
	// | `CREATING` | Creating the subaccount is in progress. |
	// | `CREATION_FAILED` | The creation operation failed, and the subaccount was not created or was created but cannot be used. |
	// | `UPDATING` | Updating the subaccount is in progress. |
	// | `UPDATE_FAILED` | The update operation failed, and the subaccount was not updated. |
	// | `UPDATE_DIRECTORY_TYPE_FAILED` | The update of the directory type failed. |
	// | `UPDATE_ACCOUNT_TYPE_FAILED` | The update of the account type failed. |
	// | `DELETING` | Deleting the subaccount is in progress. |
	// | `DELETION_FAILED` | The deletion of the subaccount failed, and the subaccount was not deleted. |
	// | `MOVING` | Moving the subaccount is in progress. |
	// | `MOVE_FAILED` | The moving of the subaccount failed. |
	// | `MOVING_TO_OTHER_GA` | Moving the subaccount to another global account is in progress. |
	// | `MOVE_TO_OTHER_GA_FAILED` | Moving the subaccount to another global account failed. |
	// | `PENDING_REVIEW` | The processing operation has been stopped for reviewing and can be restarted by the operator. |
	// | `MIGRATING` | Migrating the subaccount from Neo to Cloud Foundry. |
	// | `MIGRATED` | The migration of the subaccount completed. |
	// | `MIGRATION_FAILED` | The migration of the subaccount failed and the subaccount was not migrated. |
	// | `ROLLBACK_MIGRATION_PROCESSING` | The migration of the subaccount was rolled back and the subaccount is not migrated. |
	// | `SUSPENSION_FAILED` | The suspension operations failed. |
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) The subdomain that becomes part of the path used to access the authorization tenant of the subaccount. Must be unique within the defined region and cannot be changed after the subaccount has been created.
	// The subdomain that becomes part of the path used to access the authorization tenant of the subaccount. Must be unique within the defined region and cannot be changed after the subaccount has been created.
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`

	// critical accounts in production systems. Do not apply for subaccounts that are used for nonproduction purposes, such as development, testing, and demos. Applying this setting this does not modify the subaccount. Possible values are:
	// Shows whether the subaccount is used for production purposes. This flag can help your cloud operator to take appropriate action when handling incidents that are related to mission-critical accounts in production systems. Do not apply for subaccounts that are used for nonproduction purposes, such as development, testing, and demos. Applying this setting this does not modify the subaccount. Possible values are:
	//
	// | value | description |
	// | --- | --- |
	// | `UNSET` | Global account or subaccount admin has not set the production-relevancy flag (default value). |
	// | `NOT_USED_FOR_PRODUCTION` | The subaccount is not used for production purposes. |
	// | `USED_FOR_PRODUCTION` | The subaccount is used for production purposes. |
	Usage *string `json:"usage,omitempty" tf:"usage,omitempty"`
}

type TfSubaccountParameters struct {

	// (Boolean) Shows whether the subaccount can use beta services and applications.
	// Shows whether the subaccount can use beta services and applications.
	// +kubebuilder:validation:Optional
	BetaEnabled *bool `json:"betaEnabled,omitempty" tf:"beta_enabled,omitempty"`

	// facing UIs.
	// A description of the subaccount for customer-facing UIs.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Map of Set of String) The set of words or phrases assigned to the subaccount.
	// The set of words or phrases assigned to the subaccount.
	// +kubebuilder:validation:Optional
	Labels map[string][]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The ID of the subaccount’s parent entity. If the subaccount is located directly in the global account (not in a directory), then this is the ID of the global account.
	// The ID of the subaccount’s parent entity. If the subaccount is located directly in the global account (not in a directory), then this is the ID of the global account.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) The region in which the subaccount was created.
	// The region in which the subaccount was created.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The subdomain that becomes part of the path used to access the authorization tenant of the subaccount. Must be unique within the defined region and cannot be changed after the subaccount has been created.
	// The subdomain that becomes part of the path used to access the authorization tenant of the subaccount. Must be unique within the defined region and cannot be changed after the subaccount has been created.
	// +kubebuilder:validation:Optional
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`

	// critical accounts in production systems. Do not apply for subaccounts that are used for nonproduction purposes, such as development, testing, and demos. Applying this setting this does not modify the subaccount. Possible values are:
	// Shows whether the subaccount is used for production purposes. This flag can help your cloud operator to take appropriate action when handling incidents that are related to mission-critical accounts in production systems. Do not apply for subaccounts that are used for nonproduction purposes, such as development, testing, and demos. Applying this setting this does not modify the subaccount. Possible values are:
	//
	// | value | description |
	// | --- | --- |
	// | `UNSET` | Global account or subaccount admin has not set the production-relevancy flag (default value). |
	// | `NOT_USED_FOR_PRODUCTION` | The subaccount is not used for production purposes. |
	// | `USED_FOR_PRODUCTION` | The subaccount is used for production purposes. |
	// +kubebuilder:validation:Optional
	Usage *string `json:"usage,omitempty" tf:"usage,omitempty"`
}

// TfSubaccountSpec defines the desired state of TfSubaccount
type TfSubaccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TfSubaccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TfSubaccountInitParameters `json:"initProvider,omitempty"`
}

// TfSubaccountStatus defines the observed state of TfSubaccount.
type TfSubaccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TfSubaccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TfSubaccount is the Schema for the TfSubaccounts API. Creates a subaccount in a global account or directory. Tip: You must be assigned admin role of the global account or directory. Further documentation: https://help.sap.com/docs/btp/sap-business-technology-platform/account-model
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,account}
type TfSubaccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subdomain) || (has(self.initProvider) && has(self.initProvider.subdomain))",message="spec.forProvider.subdomain is a required parameter"
	Spec   TfSubaccountSpec   `json:"spec"`
	Status TfSubaccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TfSubaccountList contains a list of TfSubaccounts
type TfSubaccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TfSubaccount `json:"items"`
}

// Repository type metadata.
var (
	TfSubaccount_Kind             = "TfSubaccount"
	TfSubaccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TfSubaccount_Kind}.String()
	TfSubaccount_KindAPIVersion   = TfSubaccount_Kind + "." + CRDGroupVersion.String()
	TfSubaccount_GroupVersionKind = CRDGroupVersion.WithKind(TfSubaccount_Kind)
)

func init() {
	SchemeBuilder.Register(&TfSubaccount{}, &TfSubaccountList{})
}
