# This workflow will run make reviewable and make check-diff as checks

name: Reviewable&Check-Diff

on:
  workflow_call: 

env:
  GO_IMPORT_VERSION: 'v0.16.1'

jobs:
  reviewable-checkdiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: true 

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.21'

    - name: Install goimports
      run: |
        cd /tmp
        go install golang.org/x/tools/cmd/goimports@${{ env.GO_IMPORT_VERSION }}

    - name: Make Reviewable
      run: make reviewable
      env:
        RUNNING_IN_CI: 'true'
    - name: Make Check-Diff
      run: make check-diff
