# This workflow will builds a golang project and runs unit-tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Unit Tests

on:
  workflow_call: 

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: true 

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Unit-Test Init
      run: make test.init
    - name: Unit-Test Run
      run: make test.run
