# This workflow will builds a golang project and runs unit-tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Unit Tests

on:
  workflow_call: 

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: true 

    - name: Set up Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Unit-Test Init
      run: make test.init
    - name: Unit-Test Run
      run: make test.run
